version: 0.0.1.{build}
configuration: Debug
image: Visual Studio 2017

init:
  - git config --global core.autocrlf true

assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '{version}'
  assembly_file_version: '{version}'

nuget:
  account_feed: false
  project_feed: false

before_build:
- cmd: nuget restore Source\FunctionalIrbis.sln
- cmd: choco install opencover.portable
- cmd: choco install codecov

build:
  project: Source\FunctionalIrbis.sln
  publish_nuget: false

